language: node_js
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
node_js:
  - 'node'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
sudo: false
addons:
    code_climate:
        repo_token: 62c7c01e723609d3f35ab4b25318defeb38fadabf9c9c2b1e1ec229ccb6e8154
