language: node_js
script: npm run coverage
after_script: codeclimate-test-reporter < coverage/lcov.info
node_js:
 - 'node'
 - '8'
 - '7'
 - '6'
sudo: false
addons:
    code_climate:
        repo_token: 62c7c01e723609d3f35ab4b25318defeb38fadabf9c9c2b1e1ec229ccb6e8154
